### ISSUE TITLE
Setup Angular Project

### ISSUE THREAD

**Issue by algorythm** [dtugroupd/RoomLocatorWebapp#1]
* [x] Setup base project with CLI
* ~Setup NGRX~
* ~Setup a simple Hello, World with NGRX, Services~
* ~Setup structure for setting up HTTP requests to the backend~
* ~Setup procedure for sub/unsub Rx.JS~

**Comment by tlien** [comment]
Time: 40m

**Comment by algorythm** [comment]
Time: 40m

**Comment by algorythm** [comment]
Time: 40m

**Comment by algorythm** [comment]
Subtasks moved to #7
