### ISSUE TITLE
See if it's easy to upgrade to Angular 9

### ISSUE THREAD

**Issue by algorythm** [dtugroupd/RoomLocatorWebapp#59]
### Is your feature request related to a problem?
`ng build --prod` is extremely slow. Angular 9 should have fixed the build speed.

If it causes a lot of issues, don't do it. Spend at most 1-2 hours.

**Comment by Hudhud** [comment]
Angular 9 is still not fully released. It is on 9.0.0-rc.2 now.
[https://jaxenter.com/angular-v9-thread-159065.html](url)
